services:
    apache:
        image: php:8.5-apache
        container_name: file-rouge_apache
        build:
            context: ./php
        ports:
            -   "8080:80"
        volumes:
            -   ./app:/var/www/html/
        depends_on:
            -   mysql
            
    mysql:
        image: mysql:8.0
        container_name: file-rouge_mysql
        environment:
            MYSQL_ROOT_PASSWORD: adminGroup4
            MYSQL_DATABASE: eschool
            MYSQL_USER: admin
            MYSQL_PASSWORD: userGroup4
        ports:
            -   "3306:3306"
        volumes:
            -   ./mysql:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin
        container_name: file-rouge_admin
        ports:
            -   "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: adminGroup4
        depends_on:
            -   mysql
    
    postgresql:
        image: bitnami/postgresql
        container_name: file-rouge_psql
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sondageRdc
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/bitnami/postgresql
    
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@eschool.fr
            PGADMIN_DEFAULT_PASSWORD: admin4Group4
        ports:
            -   "8082:80"
        depends_on:
            -   postgresql
    
    mail_hog:
        image: mailhog/mailhog
        logging:
            driver: 'none'
        ports:
            -   "1025:1025"
            -   "8025:8025"
        

    