services:
    apache:
        image: php:8.5-apache
        container_name: eSchool_ap
        build:
            context: ./php
        ports:
            -   "8080:80"
        volumes:
            -   ./app:/var/www/html/
        depends_on:
            -   database
    
    database:
        image: mysql:8.0
        container_name: eSchool_my
        environment:
            MYSQL_ROOT_PASSWORD: adminGroup4
            MYSQL_DATABASE: eSchool
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin7791
        ports:
            -   "3306:3306"
        volumes:
            -   ./mysql:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin
        container_name: eSchool_pma
        ports:
            -   "8081:80"
        environment:
            PMA_HOST: database
            PMA_PASSWORD: adminGroup4
        depends_on:
            -   database
    
    
    mail_hog:
        image: mailhog/mailhog
        container_name: eSchool_mail
        logging:
            driver: 'none'
        ports:
            -   "1025:1025"
            -   "8025:8025"
        

    