<?php

namespace ContainerD19mZUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MSVK5D4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mSVK5D4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mSVK5D4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursesRepository' => ['privates', 'App\\Repository\\CoursesRepository', 'getCoursesRepositoryService', true],
        ], [
            'coursesRepository' => 'App\\Repository\\CoursesRepository',
        ]);
    }
}
