<?php

namespace Container0W9YEWw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MHXlpRgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mHXlpRg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mHXlpRg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CoursesController::index' => ['privates', '.service_locator.S3aWvCD.App\\Controller\\CoursesController::index()', 'getCoursesControllerindexService', true],
            'App\\Controller\\FormationController::index' => ['privates', '.service_locator.S3aWvCD.App\\Controller\\FormationController::index()', 'getFormationControllerindexService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CoursesController:index' => ['privates', '.service_locator.S3aWvCD.App\\Controller\\CoursesController::index()', 'getCoursesControllerindexService', true],
            'App\\Controller\\FormationController:index' => ['privates', '.service_locator.S3aWvCD.App\\Controller\\FormationController::index()', 'getFormationControllerindexService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.mSVK5D4.App\\Controller\\ProfileController::index()', 'getProfileControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CoursesController::index' => '?',
            'App\\Controller\\FormationController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CoursesController:index' => '?',
            'App\\Controller\\FormationController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
