<?php

namespace Container0W9YEWw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S3aWvCDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S3aWvCD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S3aWvCD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cours' => ['privates', 'App\\Entity\\Courses', 'getCoursesService', true],
        ], [
            'cours' => 'App\\Entity\\Courses',
        ]);
    }
}
