<?php

namespace Container0W9YEWw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S3aWvCD.App\Controller\CoursesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S3aWvCD.App\\Controller\\CoursesController::index()'] = ($container->privates['.service_locator.S3aWvCD'] ?? $container->load('get_ServiceLocator_S3aWvCDService'))->withContext('App\\Controller\\CoursesController::index()', $container);
    }
}
