<?php

namespace Container0W9YEWw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mSVK5D4.App\Controller\ProfileController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mSVK5D4.App\\Controller\\ProfileController::index()'] = ($container->privates['.service_locator.mSVK5D4'] ?? $container->load('get_ServiceLocator_MSVK5D4Service'))->withContext('App\\Controller\\ProfileController::index()', $container);
    }
}
